/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HostelEnterprise;
import Business.Student;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.HostelAllocationOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShelterAllocateWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kharc
 */
public class RegisterStudent extends javax.swing.JPanel {

    /**
     * Creates new form RegisterStudent
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
//    JScrollPane scrollPane = new JScrollPane(RegisterStudent);
//    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
//    scrollPane.setBounds(50, 30, 300, 50);

    public RegisterStudent(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }
    
    private boolean emailPatternCorrect() {
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(txtFieldEmailAddress.getText());
        boolean b = m.matches();
        return b;
    }

    public boolean Datevalidate() {
        Pattern pattern;
        Matcher matcher;

        pattern = Pattern.compile("(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)\\d\\d)");

        matcher = pattern.matcher(txtFieldDOB.getText());

        if (matcher.matches()) {

            matcher.reset();

            if (matcher.find()) {

                String day = matcher.group(1);
                String month = matcher.group(2);
                int year = Integer.parseInt(matcher.group(3));

                if (day.equals("31")
                        && (month.equals("4") || month.equals("6") || month.equals("9")
                        || month.equals("11") || month.equals("04") || month.equals("06")
                        || month.equals("09"))) {
                    return false; // only 1,3,5,7,8,10,12 has 31 days
                } else if (month.equals("2") || month.equals("02")) {
                    //leap year
                    if (year % 4 == 0) {
                        if (day.equals("30") || day.equals("31")) {
                            return false;
                        } else {
                            return true;
                        }
                    } else {
                        if (day.equals("29") || day.equals("30") || day.equals("31")) {
                            return false;
                        } else {
                            return true;
                        }
                    }
                } else {
                    return true;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldQualifications = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFieldAccomplishments = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        txtFieldDOB = new javax.swing.JTextField();
        txtFieldDependents = new javax.swing.JTextField();
        txtFieldCity = new javax.swing.JTextField();
        txtFieldAddress = new javax.swing.JTextField();
        txtFieldSSNNo = new javax.swing.JTextField();
        txtFieldContactNo = new javax.swing.JTextField();
        txtFieldEmailAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        radioBtnFemaleGender = new javax.swing.JRadioButton();
        radioBtnMaleGender = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFieldEmploymentStatus = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtFieldTotalIncome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioBtnCriminalCheckYes = new javax.swing.JRadioButton();
        radioBtnCriminalCheckNo = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        radioBtnillnessYes = new javax.swing.JRadioButton();
        radioBtnillnessNo = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        radioBtnCarrierYes = new javax.swing.JRadioButton();
        radioBtnCarrierNo = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        radioBtnDiseaseYes = new javax.swing.JRadioButton();
        radioBtnDiseaseNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        textFieldPrefLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(67, 67, 67))
        );

        jLabel5.setText("Any accomplishments :");

        jLabel11.setText("Date of Birth:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText(" Education Details");

        jLabel3.setText("Qualifications:");

        jLabel6.setText("Name:");

        jLabel12.setText("Gender:");

        jLabel13.setText("Dependents:");

        jLabel15.setText("Current Location:");

        jLabel31.setText("Current City:");

        jLabel14.setText("SSN");

        jLabel32.setText("Email Address:");

        jLabel34.setText("Contact Number:");

        radioBtnFemaleGender.setText("Female");
        radioBtnFemaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleGenderActionPerformed(evt);
            }
        });

        radioBtnMaleGender.setText("Male");
        radioBtnMaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleGenderActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setText(" Financial Details");

        jLabel7.setText("On-Campus Employment Status:");

        jLabel29.setText("Monthly income from all the sources:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText(" Information for Criminal Check ");

        jLabel18.setText("Have you ever pled guilty to OR being convicted OR found guilty of misdemeanor in any U.S. or non-U.S. OR military court?");

        radioBtnCriminalCheckYes.setText("Yes");
        radioBtnCriminalCheckYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCriminalCheckYesActionPerformed(evt);
            }
        });

        radioBtnCriminalCheckNo.setText("No");
        radioBtnCriminalCheckNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCriminalCheckNoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText(" Medical Details");

        btnSubmit.setBackground(new java.awt.Color(153, 255, 153));
        btnSubmit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 255, 153));
        btnBack.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel27.setText("Have you had any major illness? ");

        radioBtnillnessYes.setText("Yes");
        radioBtnillnessYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnillnessYesActionPerformed(evt);
            }
        });

        radioBtnillnessNo.setText("No");
        radioBtnillnessNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnillnessNoActionPerformed(evt);
            }
        });

        jLabel26.setText("Have you ever been told that you are a carrier of a genetic/inherited disease? ");

        radioBtnCarrierYes.setText("Yes");
        radioBtnCarrierYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCarrierYesActionPerformed(evt);
            }
        });

        radioBtnCarrierNo.setText("No");
        radioBtnCarrierNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCarrierNoActionPerformed(evt);
            }
        });

        jLabel28.setText("Have you ever been told that you have a genetic/inherited disease? ");

        radioBtnDiseaseYes.setText("Yes");
        radioBtnDiseaseYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiseaseYesActionPerformed(evt);
            }
        });

        radioBtnDiseaseNo.setText("No");
        radioBtnDiseaseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiseaseNoActionPerformed(evt);
            }
        });

        jLabel4.setText("Preferred Location:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTER STUDENT");

        jLabel1.setText("US $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43))
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldEmploymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldSSNNo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldDependents, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                            .addComponent(txtFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                            .addComponent(txtFieldContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                            .addComponent(txtFieldEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                            .addComponent(textFieldPrefLocation))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioBtnMaleGender)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioBtnFemaleGender))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldQualifications, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldAccomplishments, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnillnessYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnillnessNo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnCarrierYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnCarrierNo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnDiseaseYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnDiseaseNo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(radioBtnCriminalCheckYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnCriminalCheckNo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnMaleGender)
                    .addComponent(radioBtnFemaleGender)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldSSNNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDependents, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPrefLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldQualifications, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAccomplishments, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEmploymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnCriminalCheckYes)
                    .addComponent(radioBtnCriminalCheckNo))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioBtnillnessYes)
                        .addComponent(radioBtnillnessNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnCarrierYes)
                    .addComponent(radioBtnCarrierNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnDiseaseYes)
                    .addComponent(radioBtnDiseaseNo))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnCriminalCheckYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCriminalCheckYesActionPerformed
        // TODO add your handling code here:
        radioBtnCriminalCheckNo.setSelected(false);
    }//GEN-LAST:event_radioBtnCriminalCheckYesActionPerformed

    private void radioBtnillnessYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnillnessYesActionPerformed
        // TODO add your handling code here:
        radioBtnillnessNo.setSelected(false);
    }//GEN-LAST:event_radioBtnillnessYesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerWorkArea dwjp = (VolunteerWorkArea) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtFieldName.getText().equals("") || txtFieldDOB.getText().equals("")
                || txtFieldCity.getText().equals("")
                || txtFieldAddress.getText().equals("")
                || txtFieldSSNNo.getText().equals("")
                || txtFieldEmailAddress.getText().equals("")
                || txtFieldDependents.getText().equals("")
                || txtFieldQualifications.getText().equals("")
                || txtFieldAccomplishments.getText().equals("")
                || txtFieldEmploymentStatus.getText().equals("")
                || txtFieldTotalIncome.getText().equals("")
                || textFieldPrefLocation.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Required Fields!");
            return;
        }
        
        if(!Datevalidate()) {
            JOptionPane.showMessageDialog(null, "Date of Birth should be in the format: DD/MM/YYYY");
            return;
        }
        
        if(!emailPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Email should be in the format: <name>@<company>.<domain>");
            return;
        }

        try {
            Long.parseLong(txtFieldContactNo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Contact No");
            return;
        }
        
        if (txtFieldContactNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Contact No should be exactly 10 digits");
            return;
        }
        
        if (txtFieldSSNNo.getText().length() != 9) {
            JOptionPane.showMessageDialog(null, "Enter only 9 digits of SSN (without '-')");
            return;
        }

        try {
            Integer.parseInt(txtFieldDependents.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Dependents");
            return;
        }
        try {
            Integer.parseInt(txtFieldTotalIncome.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Income");
            return;
        }

        if (Integer.parseInt(txtFieldTotalIncome.getText()) > 1500) {
            JOptionPane.showMessageDialog(null, "The person cannot be allowed to register as his monthly income is greater than $1500.");
            return;
        }
        if (!radioBtnMaleGender.isSelected() && !radioBtnFemaleGender.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select the Gender!");
            return;
        }
        if (!radioBtnCriminalCheckYes.isSelected() && !radioBtnCriminalCheckNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for criminal record!");
            return;
        }
        if (!radioBtnillnessYes.isSelected() && !radioBtnillnessNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for illness criteria!");
            return;
        }
        if (!radioBtnCarrierYes.isSelected() && !radioBtnCarrierNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for carrier of disease!");
            return;
        }
        if (!radioBtnDiseaseYes.isSelected() && !radioBtnDiseaseNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for genetic inherited disease");
            return;
        }

        String name = txtFieldName.getText();
        String dob = txtFieldDOB.getText();
        String city = txtFieldCity.getText();
        String addresss = txtFieldAddress.getText();
        String ssnNo = txtFieldSSNNo.getText();
        String contactNo = txtFieldContactNo.getText();
        String emailAddresss = txtFieldEmailAddress.getText();
        int dependents = Integer.parseInt(txtFieldDependents.getText());
        String qualifications = txtFieldQualifications.getText();
        String accomplishments = txtFieldAccomplishments.getText();
        String employmentStatus = txtFieldEmploymentStatus.getText();
        int income = Integer.parseInt(txtFieldTotalIncome.getText());
        String prefLocation = textFieldPrefLocation.getText();
        String gender = "Male";
        if (radioBtnFemaleGender.isSelected()) {
            gender = "Female";
        }
        boolean criminalRecord = false;
        if (radioBtnCriminalCheckYes.isSelected()) {
            criminalRecord = true;
        }
        boolean majorIllnes = false;
        if (radioBtnillnessYes.isSelected()) {
            majorIllnes = true;
        }
        boolean carrierDisease = false;
        if (radioBtnCarrierYes.isSelected()) {
            carrierDisease = true;
        }
        boolean geneticDisease = false;
        if (radioBtnDiseaseYes.isSelected()) {
            geneticDisease = true;
        }
        Student person = new Student(name, dob, city, addresss, ssnNo,
                contactNo, emailAddresss, dependents, qualifications, accomplishments,
                employmentStatus, income, gender, criminalRecord, majorIllnes, carrierDisease, geneticDisease, prefLocation);
        ShelterAllocateWorkRequest request = new ShelterAllocateWorkRequest();
        request.setStudent(person);
        request.setMessage("Shelter search");
        request.setSender(userAccount);
        request.setStatus("Sent");
        Date d = new Date();
        request.setRequestDate(d);
        Organization org = null;

        for (Network network : business.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HostelEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HostelAllocationOrg) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(this, "Request Sent to Hostel Allocator!");
        clearFields();
    }//GEN-LAST:event_btnSubmitActionPerformed
    public void clearFields() {
        txtFieldName.setText("");
        txtFieldDOB.setText("");
        txtFieldCity.setText("");
        txtFieldAddress.setText("");
        txtFieldSSNNo.setText("");
        txtFieldContactNo.setText("");
        txtFieldEmailAddress.setText("");
        txtFieldDependents.setText("");
        txtFieldQualifications.setText("");
        txtFieldAccomplishments.setText("");
        txtFieldEmploymentStatus.setText("");
        txtFieldTotalIncome.setText("");
        textFieldPrefLocation.setText("");
        radioBtnMaleGender.setSelected(false);
        radioBtnFemaleGender.setSelected(false);
        radioBtnCriminalCheckYes.setSelected(false);
        radioBtnCriminalCheckNo.setSelected(false);
        radioBtnillnessYes.setSelected(false);
        radioBtnillnessNo.setSelected(false);
        radioBtnCarrierYes.setSelected(false);
        radioBtnCarrierNo.setSelected(false);
        radioBtnDiseaseYes.setSelected(false);
        radioBtnDiseaseNo.setSelected(false);

    }
    private void radioBtnMaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleGenderActionPerformed
        radioBtnFemaleGender.setSelected(false);
    }//GEN-LAST:event_radioBtnMaleGenderActionPerformed

    private void radioBtnFemaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleGenderActionPerformed
        // TODO add your handling code here:
        radioBtnMaleGender.setSelected(false);
    }//GEN-LAST:event_radioBtnFemaleGenderActionPerformed

    private void radioBtnCriminalCheckNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCriminalCheckNoActionPerformed
        // TODO add your handling code here:
        radioBtnCriminalCheckYes.setSelected(false);
    }//GEN-LAST:event_radioBtnCriminalCheckNoActionPerformed

    private void radioBtnillnessNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnillnessNoActionPerformed
        // TODO add your handling code here:
        radioBtnillnessYes.setSelected(false);
    }//GEN-LAST:event_radioBtnillnessNoActionPerformed

    private void radioBtnCarrierYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCarrierYesActionPerformed
        // TODO add your handling code here:
        radioBtnCarrierNo.setSelected(false);
    }//GEN-LAST:event_radioBtnCarrierYesActionPerformed

    private void radioBtnCarrierNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCarrierNoActionPerformed
        // TODO add your handling code here:
        radioBtnCarrierYes.setSelected(false);
    }//GEN-LAST:event_radioBtnCarrierNoActionPerformed

    private void radioBtnDiseaseYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiseaseYesActionPerformed
        // TODO add your handling code here:
        radioBtnDiseaseNo.setSelected(false);
    }//GEN-LAST:event_radioBtnDiseaseYesActionPerformed

    private void radioBtnDiseaseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiseaseNoActionPerformed
        // TODO add your handling code here:
        radioBtnDiseaseYes.setSelected(false);
    }//GEN-LAST:event_radioBtnDiseaseNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioBtnCarrierNo;
    private javax.swing.JRadioButton radioBtnCarrierYes;
    private javax.swing.JRadioButton radioBtnCriminalCheckNo;
    private javax.swing.JRadioButton radioBtnCriminalCheckYes;
    private javax.swing.JRadioButton radioBtnDiseaseNo;
    private javax.swing.JRadioButton radioBtnDiseaseYes;
    private javax.swing.JRadioButton radioBtnFemaleGender;
    private javax.swing.JRadioButton radioBtnMaleGender;
    private javax.swing.JRadioButton radioBtnillnessNo;
    private javax.swing.JRadioButton radioBtnillnessYes;
    private javax.swing.JTextField textFieldPrefLocation;
    private javax.swing.JTextField txtFieldAccomplishments;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldCity;
    private javax.swing.JTextField txtFieldContactNo;
    private javax.swing.JTextField txtFieldDOB;
    private javax.swing.JTextField txtFieldDependents;
    private javax.swing.JTextField txtFieldEmailAddress;
    private javax.swing.JTextField txtFieldEmploymentStatus;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldQualifications;
    private javax.swing.JTextField txtFieldSSNNo;
    private javax.swing.JTextField txtFieldTotalIncome;
    // End of variables declaration//GEN-END:variables
}
