/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccomodationOptions;

import Business.EcoSystem;
import Business.Enterprise.*;
import Business.Network.Network;
import Business.Organization.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HousingOptionsWorkRequest;
import Business.WorkQueue.SchemeProvisionWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kharc
 */
public class AccomodationOptionsWorkRequest extends javax.swing.JPanel {

    JPanel userProcessContainer;
    HousingOptionsWorkRequest request;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public AccomodationOptionsWorkRequest(JPanel userProcessContainer, HousingOptionsWorkRequest request, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.business = business;
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel model1 = (DefaultTableModel) tblStudentRecords1.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblStudentRecords2.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        if(request.getStudent()!=null){
            Object[] row = new Object[8];
            row[0] = request.getStudent().getName();
            row[1] = request.getStudent().getPreferredLocation();
            row[2] = request.getStudent().getCity();
            row[3] = request.getStudent().getCurrentAddress();
            row[4] = request.getStudent().getSSNNo();
            row[5] = request.getStudent().getContactNo();
            row[6] = request.getStudent().getEmailAddress();
            row[7] = request.getStudent().getDependents();
            model1.addRow(row);
            Object[] rowSecond = new Object[9];
            rowSecond[0] = request.getStudent().getQualifications();
            rowSecond[1] = request.getStudent().getAccomplishments();
            rowSecond[2] = request.getStudent().getIncome();
            rowSecond[3] = request.getStudent().getEmploymentStatus();
            rowSecond[4] = request.getStudent().getGender();
            rowSecond[5] = request.getStudent().isHasCriminalRecord()?"Yes" :"No";
            rowSecond[6] = request.getStudent().isMajorIllness()?"Yes" :"No";
            rowSecond[7] = request.getStudent().isCarrierDisease()?"Yes" :"No";
            rowSecond[8] = request.getStudent().isGeneticDisease()?"Yes" :"No";
            model2.addRow(rowSecond);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentRecords1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentRecords2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHO1 = new javax.swing.JLabel();
        txtFieldHousingOption1 = new javax.swing.JTextField();
        lblHO2 = new javax.swing.JLabel();
        txtFieldHousingOption2 = new javax.swing.JTextField();
        lblHO3 = new javax.swing.JLabel();
        txtFieldHousingOption3 = new javax.swing.JTextField();
        lblHO4 = new javax.swing.JLabel();
        txtFieldHousingOption4 = new javax.swing.JTextField();
        lblHO5 = new javax.swing.JLabel();
        txtFieldHousingOption5 = new javax.swing.JTextField();
        btnPassResults = new javax.swing.JButton();
        btnFailResults = new javax.swing.JButton();
        txtFieldHousOptionIncome1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldHousOptionIncome2 = new javax.swing.JTextField();
        txtFieldHousOptionIncome5 = new javax.swing.JTextField();
        txtFieldHousOptionIncome3 = new javax.swing.JTextField();
        txtFieldHousOptionIncome4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        resultJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(153, 255, 153));
        backJButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        tblStudentRecords1.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblStudentRecords1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Preferred Hostel", "City", "Current address", "SSN Number", "Contact Number", "Email Address", "Dependents"
            }
        ));
        jScrollPane1.setViewportView(tblStudentRecords1);

        tblStudentRecords2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblStudentRecords2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qualifications", "Accomplishments", "Income", "Employment Status", "Gender", "Criminal Record", "Major Illness", "Carrier Illness", "Genetic Illness"
            }
        ));
        jScrollPane2.setViewportView(tblStudentRecords2);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Accomodation Options Work Area");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Enter Accomodation Options based on preferred location:");

        lblHO1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHO1.setText("Accomodation Option 1");

        txtFieldHousingOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHousingOption1ActionPerformed(evt);
            }
        });

        lblHO2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHO2.setText("Accomodation Option 2");

        txtFieldHousingOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHousingOption2ActionPerformed(evt);
            }
        });

        lblHO3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHO3.setText("Accomodation Option 3");

        txtFieldHousingOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHousingOption3ActionPerformed(evt);
            }
        });

        lblHO4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHO4.setText("Accomodation Option 4");

        txtFieldHousingOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHousingOption4ActionPerformed(evt);
            }
        });

        lblHO5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblHO5.setText("Accomodation Option 5");

        txtFieldHousingOption5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHousingOption5ActionPerformed(evt);
            }
        });

        btnPassResults.setBackground(new java.awt.Color(153, 255, 153));
        btnPassResults.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnPassResults.setText("Submit Results");
        btnPassResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassResultsActionPerformed(evt);
            }
        });

        btnFailResults.setBackground(new java.awt.Color(153, 255, 153));
        btnFailResults.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnFailResults.setText("Cannot Find Accomodation");
        btnFailResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFailResultsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Addresss ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rent");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Student Details:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHO3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFieldHousingOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHO5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFieldHousingOption5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHO4)
                                                .addGap(21, 21, 21)
                                                .addComponent(txtFieldHousingOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblHO1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblHO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldHousingOption1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldHousingOption2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldHousOptionIncome1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldHousOptionIncome2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldHousOptionIncome3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldHousOptionIncome4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldHousOptionIncome5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPassResults, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnFailResults))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 553, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHO1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousingOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousOptionIncome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHO2)
                            .addComponent(txtFieldHousingOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousOptionIncome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHO3)
                            .addComponent(txtFieldHousingOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousOptionIncome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHO4)
                            .addComponent(txtFieldHousingOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousOptionIncome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldHousingOption5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldHousOptionIncome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHO5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPassResults, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFailResults, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AccomodationOptionsWorkArea dwjp = (AccomodationOptionsWorkArea) component;
        dwjp.populateReceiveTable();
        dwjp.populateSentTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void resultJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultJTextFieldActionPerformed

    private void txtFieldHousingOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHousingOption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHousingOption1ActionPerformed

    private void txtFieldHousingOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHousingOption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHousingOption2ActionPerformed

    private void txtFieldHousingOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHousingOption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHousingOption3ActionPerformed

    private void txtFieldHousingOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHousingOption4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHousingOption4ActionPerformed

    private void txtFieldHousingOption5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHousingOption5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHousingOption5ActionPerformed

    private void btnPassResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassResultsActionPerformed
        if(request.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null,"This request has already been completed by you!");
            return;
        }
        if(txtFieldHousingOption1.getText().equals("") && txtFieldHousingOption2.getText().equals("") && txtFieldHousingOption3.getText().equals("") && txtFieldHousingOption4.getText().equals("") && txtFieldHousingOption5.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Atleast provide one address to scheme option!");
            return;
        }
        List<List<String>> addresses = new ArrayList<>();
        if(!txtFieldHousingOption1.getText().equals("")){
            if(txtFieldHousOptionIncome1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter income for housing option 1!");
                return;
            }
            List<String> hop1 = new ArrayList<>();
            hop1.add(txtFieldHousingOption1.getText());
            hop1.add(txtFieldHousOptionIncome1.getText());
            addresses.add(hop1);
        }
        if(!txtFieldHousingOption2.getText().equals("")){
            if(txtFieldHousOptionIncome2.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter income for housing option 2!");
                return;
            }
            List<String> hop2 = new ArrayList<>();
            hop2.add(txtFieldHousingOption2.getText());
            hop2.add(txtFieldHousOptionIncome2.getText());
            addresses.add(hop2);
        }
        if(!txtFieldHousingOption3.getText().equals("")){
            if(txtFieldHousOptionIncome3.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter income for housing option 3!");
                return;
            }
            List<String> hop3 = new ArrayList<>();
            hop3.add(txtFieldHousingOption3.getText());
            hop3.add(txtFieldHousOptionIncome3.getText());
            addresses.add(hop3);
        }
        if(!txtFieldHousingOption4.getText().equals("")){
            if(txtFieldHousOptionIncome4.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter income for housing option 4!");
                return;
            }
            List<String> hop4 = new ArrayList<>();
            hop4.add(txtFieldHousingOption4.getText());
            hop4.add(txtFieldHousOptionIncome4.getText());
            addresses.add(hop4);
        }
        if(!txtFieldHousingOption5.getText().equals("")){
            if(txtFieldHousOptionIncome5.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter income for housing option 3!");
                return;
            }
            List<String> hop5 = new ArrayList<>();
            hop5.add(txtFieldHousingOption5.getText());
            hop5.add(txtFieldHousOptionIncome5.getText());
            addresses.add(hop5);
        }
        request.setStatus("Completed");
        request.setTestResult("Sent to SP");
        request.getShelterAllocWorkReq().setTestResult("Completed by Room Options and and sent to Scheme Provision");
        UserAccount account = new UserAccount();
        account.setUsername("None");
        request.getShelterAllocWorkReq().setReceiver(account);
        SchemeProvisionWorkRequest fcRequest = new SchemeProvisionWorkRequest();
        fcRequest.setMessage("Provide Schemes");
        fcRequest.setSender(userAccount);
        fcRequest.setStatus("Sent");
        fcRequest.setStudent(request.getStudent());
        fcRequest.setShelterAllocWorkReq(request.getShelterAllocWorkReq());
        fcRequest.setAddressesForStudent(addresses);
        Date d = new Date();
        fcRequest.setRequestDate(d);
        Organization org = null;

        for (Network network : business.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof RoomEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof SchemeProvisionOrg) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(fcRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(fcRequest);
            JOptionPane.showMessageDialog(this, "Request Sent to Scheme Provision Organization");
        }
    }//GEN-LAST:event_btnPassResultsActionPerformed

    private void btnFailResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFailResultsActionPerformed
        if(request.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null,"This request has already been completed by you!");
            return;
        }
        UserAccount account = new UserAccount();
        account.setUsername("None");
        request.getShelterAllocWorkReq().setReceiver(account);
        request.getShelterAllocWorkReq().setTestResult("The request has been denied by Room Options!");
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(null,"Volunteer has been informed abt failure!");
    }//GEN-LAST:event_btnFailResultsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnFailResults;
    private javax.swing.JButton btnPassResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHO1;
    private javax.swing.JLabel lblHO2;
    private javax.swing.JLabel lblHO3;
    private javax.swing.JLabel lblHO4;
    private javax.swing.JLabel lblHO5;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JTable tblStudentRecords1;
    private javax.swing.JTable tblStudentRecords2;
    private javax.swing.JTextField txtFieldHousOptionIncome1;
    private javax.swing.JTextField txtFieldHousOptionIncome2;
    private javax.swing.JTextField txtFieldHousOptionIncome3;
    private javax.swing.JTextField txtFieldHousOptionIncome4;
    private javax.swing.JTextField txtFieldHousOptionIncome5;
    private javax.swing.JTextField txtFieldHousingOption1;
    private javax.swing.JTextField txtFieldHousingOption2;
    private javax.swing.JTextField txtFieldHousingOption3;
    private javax.swing.JTextField txtFieldHousingOption4;
    private javax.swing.JTextField txtFieldHousingOption5;
    // End of variables declaration//GEN-END:variables
}
