/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HostelAllocatorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HostelEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.HostelFacilitationOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShelterAllocateWorkRequest;
import Business.WorkQueue.ShelterFacilitateWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayur
 */
public class HostelAllocatorWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ShelterAllocateWorkRequest request;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form ShelterAllocatorWorkRequestJPanel
     */
    public HostelAllocatorWorkRequestJPanel(JPanel userProcessContainer, ShelterAllocateWorkRequest request, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = account;
        this.business = business;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblStudentRecords1.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblStudentRecords2.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        if (request.getStudent() != null) {
            Object[] row = new Object[8];
            row[0] = request.getStudent().getName();
            row[1] = request.getStudent().getDob();
            row[2] = request.getStudent().getCity();
            row[3] = request.getStudent().getCurrentAddress();
            row[4] = request.getStudent().getSSNNo();
            row[5] = request.getStudent().getContactNo();
            row[6] = request.getStudent().getEmailAddress();
            row[7] = request.getStudent().getDependents();
            model1.addRow(row);
            Object[] rowSecond = new Object[9];
            rowSecond[0] = request.getStudent().getQualifications();
            rowSecond[1] = request.getStudent().getAccomplishments();
            rowSecond[2] = request.getStudent().getIncome();
            rowSecond[3] = request.getStudent().getEmploymentStatus();
            rowSecond[4] = request.getStudent().getGender();
            rowSecond[5] = request.getStudent().isHasCriminalRecord() ? "Yes" : "No";
            rowSecond[6] = request.getStudent().isMajorIllness() ? "Yes" : "No";
            rowSecond[7] = request.getStudent().isCarrierDisease() ? "Yes" : "No";
            rowSecond[8] = request.getStudent().isGeneticDisease() ? "Yes" : "No";
            model2.addRow(rowSecond);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentRecords2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentRecords1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFieldAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HOSTEL ALLOCATOR");

        tblStudentRecords2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblStudentRecords2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qualifications", "Accomplishments", "Income", "Employment Status", "Gender", "Criminal Record", "Major Illness", "Carrier Illness", "Genetic Illness"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudentRecords2);
        if (tblStudentRecords2.getColumnModel().getColumnCount() > 0) {
            tblStudentRecords2.getColumnModel().getColumn(0).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(1).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(2).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(3).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(4).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(5).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(6).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(7).setResizable(false);
            tblStudentRecords2.getColumnModel().getColumn(8).setResizable(false);
        }

        tblStudentRecords1.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblStudentRecords1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "City", "Current Address", "SSN", "Contact No", "Email Address", "Dependents"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudentRecords1);
        if (tblStudentRecords1.getColumnModel().getColumnCount() > 0) {
            tblStudentRecords1.getColumnModel().getColumn(0).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(1).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(2).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(3).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(4).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(5).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(6).setResizable(false);
            tblStudentRecords1.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("Enter Hostel Address:");

        txtFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAddressActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(153, 255, 153));
        btnSubmit.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Hostel will be allocated to below Student:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAddressActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null,"This request has already been completed by you!");
            return;
        }
        if(txtFieldAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter the address field to proceed the request!");
            return;
        }
        request.setTestResult("Sent to SA");
        request.setStatus("Completed");
        UserAccount account = new UserAccount();
        account.setUsername("None");
        request.setReceiver(account);
        request.setTestResult("Completed by Hostel Allocator and passed to Hostel Facilitator");
        ShelterFacilitateWorkRequest sfRequest = new ShelterFacilitateWorkRequest();
        sfRequest.setMessage("Shelter Facilitation");
        sfRequest.setShelterAllocWorkReq(request);
        sfRequest.setStudent(request.getStudent());
        sfRequest.setAddressToBePlaced(txtFieldAddress.getText());
        sfRequest.setSender(userAccount);
        sfRequest.setStatus("Sent");
        Date d = new Date();
        sfRequest.setRequestDate(d);
        Organization org = null;

        for (Network network : business.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HostelEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HostelFacilitationOrg) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(sfRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(sfRequest);
            JOptionPane.showMessageDialog(this, "Request Sent to Hostel Facilitator");

        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HostelAllocatorWorkArea wp = (HostelAllocatorWorkArea) component;
        wp.populateReceiveTable();
        wp.populateSentTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStudentRecords1;
    private javax.swing.JTable tblStudentRecords2;
    private javax.swing.JTextField txtFieldAddress;
    // End of variables declaration//GEN-END:variables
}
